export const POSTS_LIST_REQUEST = 'POSTS_LIST_REQUEST';
export const POSTS_LIST_SUCCESS = 'POSTS_LIST_SUCCESS';
export const POSTS_LIST_FAILURE = 'POSTS_LIST_FAILURE';

export const POSTS_GET_REQUEST = 'POSTS_GET_REQUEST';
export const POSTS_GET_SUCCESS = 'POSTS_GET_SUCCESS';
export const POSTS_GET_FAILURE = 'POSTS_GET_FAILURE';

export const POSTS_UPDATE_REQUEST = 'POSTS_UPDATE_REQUEST';
export const POSTS_UPDATE_SUCCESS = 'POSTS_UPDATE_SUCCESS';
export const POSTS_UPDATE_FAILURE = 'POSTS_UPDATE_FAILURE';

export const POSTS_DELETE_REQUEST = 'POSTS_DELETE_REQUEST';
export const POSTS_DELETE_SUCCESS = 'POSTS_DELETE_SUCCESS';
export const POSTS_DELETE_FAILURE = 'POSTS_DELETE_FAILURE';

export const POSTS_COMMENT_GET_REQUEST = 'POSTS_COMMENT_GET_REQUEST';
export const POSTS_COMMENT_GET_SUCCESS = 'POSTS_COMMENT_GET_SUCCESS';
export const POSTS_COMMENT_GET_FAILURE = 'POSTS_COMMENT_GET_FAILURE';